/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Attachment = IDL.Record({
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
});
export const CoachProfile = IDL.Record({
  'bio' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'coachingRoles' : IDL.Vec(IDL.Text),
  'experience' : IDL.Nat,
  'specialty' : IDL.Text,
  'positionsCoached' : IDL.Vec(IDL.Text),
  'photo' : IDL.Opt(ExternalBlob),
  'certifications' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Application = IDL.Record({
  'applicant' : IDL.Principal,
  'coverLetter' : IDL.Text,
  'timestamp' : Time,
  'profile' : CoachProfile,
});
export const JobPost = IDL.Record({
  'id' : IDL.Text,
  'additionalInfo' : IDL.Text,
  'compensation' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'schoolOrOrganization' : IDL.Text,
  'role' : IDL.Text,
  'level' : IDL.Text,
  'timestamp' : Time,
  'requirements' : IDL.Text,
  'applications' : IDL.Vec(Application),
  'location' : IDL.Text,
  'poster' : IDL.Principal,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'comments' : IDL.Vec(Comment),
  'attachments' : IDL.Vec(Attachment),
});
export const CoachProfileDetail = IDL.Record({
  'jobs' : IDL.Vec(JobPost),
  'followersCount' : IDL.Nat,
  'isAdmin' : IDL.Bool,
  'followingCount' : IDL.Nat,
  'comments' : IDL.Vec(Comment),
  'posts' : IDL.Vec(Post),
  'followers' : IDL.Vec(IDL.Principal),
  'following' : IDL.Vec(IDL.Principal),
  'profile' : CoachProfile,
});
export const DirectMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const GroupMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'groupId' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'applyForJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'connectWithCoach' : IDL.Func([IDL.Principal], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Vec(Attachment)], [], []),
  'createProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteJobPosting' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'dismissBannerNotification' : IDL.Func([], [], []),
  'followCoach' : IDL.Func([IDL.Principal], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(CoachProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CoachProfile)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCoachPhoto' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getCoachProfileDetail' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CoachProfileDetail)],
      ['query'],
    ),
  'getConnections' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getFeedCategories' : IDL.Func(
      [],
      [IDL.Record({ 'following' : IDL.Vec(Post), 'forYou' : IDL.Vec(Post) })],
      ['query'],
    ),
  'getFollowerDetails' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [
        IDL.Bool,
        IDL.Vec(IDL.Tuple(IDL.Principal, CoachProfile)),
        IDL.Vec(IDL.Tuple(IDL.Principal, CoachProfile)),
      ],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getGroupMessages' : IDL.Func([IDL.Text], [IDL.Vec(GroupMessage)], ['query']),
  'getJobApplications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getJobPostings' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
  'getMyApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Application))],
      ['query'],
    ),
  'getMyConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getPostAttachments' : IDL.Func([IDL.Text], [IDL.Vec(Attachment)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(CoachProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CoachProfile)],
      ['query'],
    ),
  'hasNewBannerNotification' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeCallerProfile' : IDL.Func([], [IDL.Opt(CoachProfile)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'markPostViewed' : IDL.Func([IDL.Text], [], []),
  'markPostsViewed' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'postJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([CoachProfile], [], []),
  'saveProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitReport' : IDL.Func([], [], []),
  'toggleLikeComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'toggleLikePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'unfollowCoach' : IDL.Func([IDL.Principal], [], []),
  'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Attachment)], [], []),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Attachment = IDL.Record({
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
  });
  const CoachProfile = IDL.Record({
    'bio' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'coachingRoles' : IDL.Vec(IDL.Text),
    'experience' : IDL.Nat,
    'specialty' : IDL.Text,
    'positionsCoached' : IDL.Vec(IDL.Text),
    'photo' : IDL.Opt(ExternalBlob),
    'certifications' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Application = IDL.Record({
    'applicant' : IDL.Principal,
    'coverLetter' : IDL.Text,
    'timestamp' : Time,
    'profile' : CoachProfile,
  });
  const JobPost = IDL.Record({
    'id' : IDL.Text,
    'additionalInfo' : IDL.Text,
    'compensation' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'schoolOrOrganization' : IDL.Text,
    'role' : IDL.Text,
    'level' : IDL.Text,
    'timestamp' : Time,
    'requirements' : IDL.Text,
    'applications' : IDL.Vec(Application),
    'location' : IDL.Text,
    'poster' : IDL.Principal,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'comments' : IDL.Vec(Comment),
    'attachments' : IDL.Vec(Attachment),
  });
  const CoachProfileDetail = IDL.Record({
    'jobs' : IDL.Vec(JobPost),
    'followersCount' : IDL.Nat,
    'isAdmin' : IDL.Bool,
    'followingCount' : IDL.Nat,
    'comments' : IDL.Vec(Comment),
    'posts' : IDL.Vec(Post),
    'followers' : IDL.Vec(IDL.Principal),
    'following' : IDL.Vec(IDL.Principal),
    'profile' : CoachProfile,
  });
  const DirectMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const GroupMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'groupId' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'applyForJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'connectWithCoach' : IDL.Func([IDL.Principal], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Vec(Attachment)], [], []),
    'createProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteJobPosting' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'dismissBannerNotification' : IDL.Func([], [], []),
    'followCoach' : IDL.Func([IDL.Principal], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(CoachProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CoachProfile)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCoachPhoto' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getCoachProfileDetail' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CoachProfileDetail)],
        ['query'],
      ),
    'getConnections' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getFeedCategories' : IDL.Func(
        [],
        [IDL.Record({ 'following' : IDL.Vec(Post), 'forYou' : IDL.Vec(Post) })],
        ['query'],
      ),
    'getFollowerDetails' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [
          IDL.Bool,
          IDL.Vec(IDL.Tuple(IDL.Principal, CoachProfile)),
          IDL.Vec(IDL.Tuple(IDL.Principal, CoachProfile)),
        ],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowersCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowingCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getJobPostings' : IDL.Func([], [IDL.Vec(JobPost)], ['query']),
    'getMyApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Application))],
        ['query'],
      ),
    'getMyConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getPostAttachments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attachment)],
        ['query'],
      ),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CoachProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CoachProfile)],
        ['query'],
      ),
    'hasNewBannerNotification' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeCallerProfile' : IDL.Func([], [IDL.Opt(CoachProfile)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'markPostViewed' : IDL.Func([IDL.Text], [], []),
    'markPostsViewed' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'postJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([CoachProfile], [], []),
    'saveProfilePhoto' : IDL.Func([ExternalBlob], [], []),
    'sendDirectMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitReport' : IDL.Func([], [], []),
    'toggleLikeComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'toggleLikePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'unfollowCoach' : IDL.Func([IDL.Principal], [], []),
    'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Attachment)], [], []),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };