/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'applicant' : Principal,
  'coverLetter' : string,
  'timestamp' : Time,
  'profile' : CoachProfile,
}
export interface Attachment {
  'blob' : ExternalBlob,
  'mimeType' : string,
  'fileName' : string,
}
export interface CoachProfile {
  'bio' : string,
  'userId' : Principal,
  'name' : string,
  'coachingRoles' : Array<string>,
  'experience' : bigint,
  'specialty' : string,
  'positionsCoached' : Array<string>,
  'photo' : [] | [ExternalBlob],
  'certifications' : Array<string>,
  'location' : string,
}
export interface CoachProfileDetail {
  'jobs' : Array<JobPost>,
  'followersCount' : bigint,
  'isAdmin' : boolean,
  'followingCount' : bigint,
  'comments' : Array<Comment>,
  'posts' : Array<Post>,
  'followers' : Array<Principal>,
  'following' : Array<Principal>,
  'profile' : CoachProfile,
}
export interface Comment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
}
export interface DirectMessage {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface GroupMessage {
  'content' : string,
  'sender' : Principal,
  'groupId' : string,
  'timestamp' : Time,
}
export interface JobPost {
  'id' : string,
  'additionalInfo' : string,
  'compensation' : [] | [string],
  'title' : string,
  'schoolOrOrganization' : string,
  'role' : string,
  'level' : string,
  'timestamp' : Time,
  'requirements' : string,
  'applications' : Array<Application>,
  'location' : string,
  'poster' : Principal,
}
export interface Post {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
  'comments' : Array<Comment>,
  'attachments' : Array<Attachment>,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'applyForJob' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'connectWithCoach' : ActorMethod<[Principal], undefined>,
  'createPost' : ActorMethod<[string, Array<Attachment>], undefined>,
  'createProfile' : ActorMethod<
    [
      string,
      bigint,
      string,
      Array<string>,
      [] | [ExternalBlob],
      string,
      Array<string>,
      string,
      Array<string>,
    ],
    undefined
  >,
  'deleteComment' : ActorMethod<[string, string], undefined>,
  'deleteJobPosting' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'dismissBannerNotification' : ActorMethod<[], undefined>,
  'followCoach' : ActorMethod<[Principal], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<CoachProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CoachProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachCount' : ActorMethod<[], bigint>,
  'getCoachPhoto' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getCoachProfileDetail' : ActorMethod<[Principal], [] | [CoachProfileDetail]>,
  'getConnections' : ActorMethod<[Principal], Array<Principal>>,
  'getDirectMessages' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getFeedCategories' : ActorMethod<
    [],
    { 'following' : Array<Post>, 'forYou' : Array<Post> }
  >,
  'getFollowerDetails' : ActorMethod<
    [Principal, Principal],
    [
      boolean,
      Array<[Principal, CoachProfile]>,
      Array<[Principal, CoachProfile]>,
    ]
  >,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowersCount' : ActorMethod<[Principal], bigint>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowingCount' : ActorMethod<[Principal], bigint>,
  'getGroupMessages' : ActorMethod<[string], Array<GroupMessage>>,
  'getJobApplications' : ActorMethod<[string], Array<Application>>,
  'getJobPostings' : ActorMethod<[], Array<JobPost>>,
  'getMyApplications' : ActorMethod<[], Array<[string, Application]>>,
  'getMyConnections' : ActorMethod<[], Array<Principal>>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getPostAttachments' : ActorMethod<[string], Array<Attachment>>,
  'getProfile' : ActorMethod<[Principal], [] | [CoachProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CoachProfile]>,
  'hasNewBannerNotification' : ActorMethod<[], boolean>,
  'initializeCallerProfile' : ActorMethod<[], [] | [CoachProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal, Principal], boolean>,
  'markPostViewed' : ActorMethod<[string], undefined>,
  'markPostsViewed' : ActorMethod<[Array<string>], undefined>,
  'postJob' : ActorMethod<
    [string, string, string, string, string, [] | [string], string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[CoachProfile], undefined>,
  'saveProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'sendDirectMessage' : ActorMethod<[Principal, string], undefined>,
  'sendGroupMessage' : ActorMethod<[string, string], undefined>,
  'submitReport' : ActorMethod<[], undefined>,
  'toggleLikeComment' : ActorMethod<[string, string], boolean>,
  'toggleLikePost' : ActorMethod<[string], boolean>,
  'unfollowCoach' : ActorMethod<[Principal], undefined>,
  'updatePost' : ActorMethod<[string, string, Array<Attachment>], undefined>,
  'updateProfile' : ActorMethod<
    [
      string,
      bigint,
      string,
      Array<string>,
      [] | [ExternalBlob],
      string,
      Array<string>,
      string,
      Array<string>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];