/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CoachProfileDetail {
    jobs: Array<JobPost>;
    followersCount: bigint;
    isAdmin: boolean;
    followingCount: bigint;
    comments: Array<Comment>;
    posts: Array<Post>;
    followers: Array<Principal>;
    following: Array<Principal>;
    profile: CoachProfile;
}
export interface DirectMessage {
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export interface Application {
    applicant: Principal;
    coverLetter: string;
    timestamp: Time;
    profile: CoachProfile;
}
export type Time = bigint;
export interface GroupMessage {
    content: string;
    sender: Principal;
    groupId: string;
    timestamp: Time;
}
export interface JobPost {
    id: string;
    additionalInfo: string;
    compensation?: string;
    title: string;
    schoolOrOrganization: string;
    role: string;
    level: string;
    timestamp: Time;
    requirements: string;
    applications: Array<Application>;
    location: string;
    poster: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Comment {
    id: string;
    content: string;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Post {
    id: string;
    content: string;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
    comments: Array<Comment>;
    attachments: Array<Attachment>;
}
export interface Attachment {
    blob: ExternalBlob;
    mimeType: string;
    fileName: string;
}
export interface CoachProfile {
    bio: string;
    userId: Principal;
    name: string;
    coachingRoles: Array<string>;
    experience: bigint;
    specialty: string;
    positionsCoached: Array<string>;
    photo?: ExternalBlob;
    certifications: Array<string>;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(postId: string, content: string): Promise<void>;
    applyForJob(jobId: string, coverLetter: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    connectWithCoach(coachId: Principal): Promise<void>;
    createPost(content: string, attachments: Array<Attachment>): Promise<void>;
    createProfile(name: string, experience: bigint, specialty: string, certifications: Array<string>, photo: ExternalBlob | null, bio: string, positionsCoached: Array<string>, location: string, coachingRoles: Array<string>): Promise<void>;
    deleteComment(postId: string, commentId: string): Promise<void>;
    deleteJobPosting(jobId: string): Promise<void>;
    deletePost(postId: string): Promise<void>;
    deleteUser(target: Principal): Promise<void>;
    dismissBannerNotification(): Promise<void>;
    followCoach(coachToFollow: Principal): Promise<void>;
    getAllProfiles(): Promise<Array<CoachProfile>>;
    getCallerUserProfile(): Promise<CoachProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoachCount(): Promise<bigint>;
    getCoachPhoto(coachId: Principal): Promise<ExternalBlob | null>;
    getCoachProfileDetail(coachId: Principal): Promise<CoachProfileDetail | null>;
    getConnections(userId: Principal): Promise<Array<Principal>>;
    getDirectMessages(otherUser: Principal): Promise<Array<DirectMessage>>;
    getFeed(): Promise<Array<Post>>;
    getFeedCategories(): Promise<{
        following: Array<Post>;
        forYou: Array<Post>;
    }>;
    getFollowerDetails(followerId: Principal, coachId: Principal): Promise<[boolean, Array<[Principal, CoachProfile]>, Array<[Principal, CoachProfile]>]>;
    getFollowers(coachId: Principal): Promise<Array<Principal>>;
    getFollowersCount(coachId: Principal): Promise<bigint>;
    getFollowing(coachId: Principal): Promise<Array<Principal>>;
    getFollowingCount(coachId: Principal): Promise<bigint>;
    getGroupMessages(groupId: string): Promise<Array<GroupMessage>>;
    getJobApplications(jobId: string): Promise<Array<Application>>;
    getJobPostings(): Promise<Array<JobPost>>;
    getMyApplications(): Promise<Array<[string, Application]>>;
    getMyConnections(): Promise<Array<Principal>>;
    getPost(postId: string): Promise<Post | null>;
    getPostAttachments(postId: string): Promise<Array<Attachment>>;
    getProfile(userId: Principal): Promise<CoachProfile | null>;
    getUserProfile(user: Principal): Promise<CoachProfile | null>;
    hasNewBannerNotification(): Promise<boolean>;
    initializeCallerProfile(): Promise<CoachProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(callerId: Principal, coachId: Principal): Promise<boolean>;
    markPostViewed(postId: string): Promise<void>;
    markPostsViewed(postIds: Array<string>): Promise<void>;
    postJob(title: string, role: string, level: string, schoolOrOrganization: string, location: string, compensation: string | null, requirements: string, additionalInfo: string): Promise<void>;
    saveCallerUserProfile(profile: CoachProfile): Promise<void>;
    saveProfilePhoto(photo: ExternalBlob): Promise<void>;
    sendDirectMessage(receiver: Principal, content: string): Promise<void>;
    sendGroupMessage(groupId: string, content: string): Promise<void>;
    submitReport(): Promise<void>;
    toggleLikeComment(postId: string, commentId: string): Promise<boolean>;
    toggleLikePost(postId: string): Promise<boolean>;
    unfollowCoach(coachToUnfollow: Principal): Promise<void>;
    updatePost(postId: string, newContent: string, newAttachments: Array<Attachment>): Promise<void>;
    updateProfile(name: string, experience: bigint, specialty: string, certifications: Array<string>, photo: ExternalBlob | null, bio: string, positionsCoached: Array<string>, location: string, coachingRoles: Array<string>): Promise<void>;
}
import type { Application as _Application, Attachment as _Attachment, CoachProfile as _CoachProfile, CoachProfileDetail as _CoachProfileDetail, Comment as _Comment, ExternalBlob as _ExternalBlob, JobPost as _JobPost, Post as _Post, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async applyForJob(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async connectWithCoach(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectWithCoach(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectWithCoach(arg0);
            return result;
        }
    }
    async createPost(arg0: string, arg1: Array<Attachment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: bigint, arg2: string, arg3: Array<string>, arg4: ExternalBlob | null, arg5: string, arg6: Array<string>, arg7: string, arg8: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2, arg3, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2, arg3, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0, arg1);
            return result;
        }
    }
    async deleteJobPosting(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobPosting(arg0);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async dismissBannerNotification(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissBannerNotification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissBannerNotification();
            return result;
        }
    }
    async followCoach(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followCoach(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followCoach(arg0);
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<CoachProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<CoachProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachCount();
            return result;
        }
    }
    async getCoachPhoto(arg0: Principal): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachPhoto(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachPhoto(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachProfileDetail(arg0: Principal): Promise<CoachProfileDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachProfileDetail(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachProfileDetail(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnections(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnections(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnections(arg0);
            return result;
        }
    }
    async getDirectMessages(arg0: Principal): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessages(arg0);
            return result;
        }
    }
    async getFeed(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedCategories(): Promise<{
        following: Array<Post>;
        forYou: Array<Post>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedCategories();
                return from_candid_record_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedCategories();
            return from_candid_record_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowerDetails(arg0: Principal, arg1: Principal): Promise<[boolean, Array<[Principal, CoachProfile]>, Array<[Principal, CoachProfile]>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowerDetails(arg0, arg1);
                return [
                    result[0],
                    from_candid_vec_n40(this._uploadFile, this._downloadFile, result[1]),
                    from_candid_vec_n40(this._uploadFile, this._downloadFile, result[2])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowerDetails(arg0, arg1);
            return [
                result[0],
                from_candid_vec_n40(this._uploadFile, this._downloadFile, result[1]),
                from_candid_vec_n40(this._uploadFile, this._downloadFile, result[2])
            ];
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getFollowersCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowersCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowersCount(arg0);
            return result;
        }
    }
    async getFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0);
            return result;
        }
    }
    async getFollowingCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowingCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowingCount(arg0);
            return result;
        }
    }
    async getGroupMessages(arg0: string): Promise<Array<GroupMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessages(arg0);
            return result;
        }
    }
    async getJobApplications(arg0: string): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobApplications(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobApplications(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPostings(): Promise<Array<JobPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPostings();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPostings();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<[string, Application]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyConnections(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyConnections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyConnections();
            return result;
        }
    }
    async getPost(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostAttachments(arg0: string): Promise<Array<Attachment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostAttachments(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostAttachments(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<CoachProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<CoachProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasNewBannerNotification(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasNewBannerNotification();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasNewBannerNotification();
            return result;
        }
    }
    async initializeCallerProfile(): Promise<CoachProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeCallerProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeCallerProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0, arg1);
            return result;
        }
    }
    async markPostViewed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPostViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPostViewed(arg0);
            return result;
        }
    }
    async markPostsViewed(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPostsViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPostsViewed(arg0);
            return result;
        }
    }
    async postJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postJob(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n45(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJob(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n45(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: CoachProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_CoachProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_CoachProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProfilePhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfilePhoto(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfilePhoto(await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendDirectMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0, arg1);
            return result;
        }
    }
    async sendGroupMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGroupMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGroupMessage(arg0, arg1);
            return result;
        }
    }
    async submitReport(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport();
            return result;
        }
    }
    async toggleLikeComment(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLikeComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLikeComment(arg0, arg1);
            return result;
        }
    }
    async toggleLikePost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLikePost(arg0);
            return result;
        }
    }
    async unfollowCoach(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowCoach(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowCoach(arg0);
            return result;
        }
    }
    async updatePost(arg0: string, arg1: string, arg2: Array<Attachment>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, arg1, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, arg1, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: bigint, arg2: string, arg3: Array<string>, arg4: ExternalBlob | null, arg5: string, arg6: Array<string>, arg7: string, arg8: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
async function from_candid_Application_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Promise<Application> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Attachment_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attachment): Promise<Attachment> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_CoachProfileDetail_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoachProfileDetail): Promise<CoachProfileDetail> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_CoachProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoachProfile): Promise<CoachProfile> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_JobPost_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPost): Promise<JobPost> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Post_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Promise<Post> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoachProfile]): Promise<CoachProfile | null> {
    return value.length === 0 ? null : await from_candid_CoachProfile_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoachProfileDetail]): Promise<CoachProfileDetail | null> {
    return value.length === 0 ? null : await from_candid_CoachProfileDetail_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Promise<Post | null> {
    return value.length === 0 ? null : await from_candid_Post_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    userId: Principal;
    name: string;
    coachingRoles: Array<string>;
    experience: bigint;
    specialty: string;
    positionsCoached: Array<string>;
    photo: [] | [_ExternalBlob];
    certifications: Array<string>;
    location: string;
}): Promise<{
    bio: string;
    userId: Principal;
    name: string;
    coachingRoles: Array<string>;
    experience: bigint;
    specialty: string;
    positionsCoached: Array<string>;
    photo?: ExternalBlob;
    certifications: Array<string>;
    location: string;
}> {
    return {
        bio: value.bio,
        userId: value.userId,
        name: value.name,
        coachingRoles: value.coachingRoles,
        experience: value.experience,
        specialty: value.specialty,
        positionsCoached: value.positionsCoached,
        photo: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.photo)),
        certifications: value.certifications,
        location: value.location
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobs: Array<_JobPost>;
    followersCount: bigint;
    isAdmin: boolean;
    followingCount: bigint;
    comments: Array<_Comment>;
    posts: Array<_Post>;
    followers: Array<Principal>;
    following: Array<Principal>;
    profile: _CoachProfile;
}): Promise<{
    jobs: Array<JobPost>;
    followersCount: bigint;
    isAdmin: boolean;
    followingCount: bigint;
    comments: Array<Comment>;
    posts: Array<Post>;
    followers: Array<Principal>;
    following: Array<Principal>;
    profile: CoachProfile;
}> {
    return {
        jobs: await from_candid_vec_n26(_uploadFile, _downloadFile, value.jobs),
        followersCount: value.followersCount,
        isAdmin: value.isAdmin,
        followingCount: value.followingCount,
        comments: value.comments,
        posts: await from_candid_vec_n33(_uploadFile, _downloadFile, value.posts),
        followers: value.followers,
        following: value.following,
        profile: await from_candid_CoachProfile_n16(_uploadFile, _downloadFile, value.profile)
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    additionalInfo: string;
    compensation: [] | [string];
    title: string;
    schoolOrOrganization: string;
    role: string;
    level: string;
    timestamp: _Time;
    requirements: string;
    applications: Array<_Application>;
    location: string;
    poster: Principal;
}): Promise<{
    id: string;
    additionalInfo: string;
    compensation?: string;
    title: string;
    schoolOrOrganization: string;
    role: string;
    level: string;
    timestamp: Time;
    requirements: string;
    applications: Array<Application>;
    location: string;
    poster: Principal;
}> {
    return {
        id: value.id,
        additionalInfo: value.additionalInfo,
        compensation: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.compensation)),
        title: value.title,
        schoolOrOrganization: value.schoolOrOrganization,
        role: value.role,
        level: value.level,
        timestamp: value.timestamp,
        requirements: value.requirements,
        applications: await from_candid_vec_n30(_uploadFile, _downloadFile, value.applications),
        location: value.location,
        poster: value.poster
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    applicant: Principal;
    coverLetter: string;
    timestamp: _Time;
    profile: _CoachProfile;
}): Promise<{
    applicant: Principal;
    coverLetter: string;
    timestamp: Time;
    profile: CoachProfile;
}> {
    return {
        applicant: value.applicant,
        coverLetter: value.coverLetter,
        timestamp: value.timestamp,
        profile: await from_candid_CoachProfile_n16(_uploadFile, _downloadFile, value.profile)
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    author: Principal;
    likes: Array<Principal>;
    timestamp: _Time;
    comments: Array<_Comment>;
    attachments: Array<_Attachment>;
}): Promise<{
    id: string;
    content: string;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
    comments: Array<Comment>;
    attachments: Array<Attachment>;
}> {
    return {
        id: value.id,
        content: value.content,
        author: value.author,
        likes: value.likes,
        timestamp: value.timestamp,
        comments: value.comments,
        attachments: await from_candid_vec_n36(_uploadFile, _downloadFile, value.attachments)
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    mimeType: string;
    fileName: string;
}): Promise<{
    blob: ExternalBlob;
    mimeType: string;
    fileName: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.blob),
        mimeType: value.mimeType,
        fileName: value.fileName
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    following: Array<_Post>;
    forYou: Array<_Post>;
}): Promise<{
    following: Array<Post>;
    forYou: Array<Post>;
}> {
    return {
        following: await from_candid_vec_n33(_uploadFile, _downloadFile, value.following),
        forYou: await from_candid_vec_n33(_uploadFile, _downloadFile, value.forYou)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _CoachProfile]): Promise<[Principal, CoachProfile]> {
    return [
        value[0],
        await from_candid_CoachProfile_n16(_uploadFile, _downloadFile, value[1])
    ];
}
async function from_candid_tuple_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Application]): Promise<[string, Application]> {
    return [
        value[0],
        await from_candid_Application_n31(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoachProfile>): Promise<Array<CoachProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CoachProfile_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPost>): Promise<Array<JobPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_JobPost_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Promise<Array<Application>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Application_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Promise<Array<Post>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Post_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attachment>): Promise<Array<Attachment>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Attachment_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _CoachProfile]>): Promise<Array<[Principal, CoachProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n41(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Application]>): Promise<Array<[string, Application]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n43(_uploadFile, _downloadFile, x)));
}
async function to_candid_Attachment_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attachment): Promise<_Attachment> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_CoachProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoachProfile): Promise<_CoachProfile> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    mimeType: string;
    fileName: string;
}): Promise<{
    blob: _ExternalBlob;
    mimeType: string;
    fileName: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.blob),
        mimeType: value.mimeType,
        fileName: value.fileName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    userId: Principal;
    name: string;
    coachingRoles: Array<string>;
    experience: bigint;
    specialty: string;
    positionsCoached: Array<string>;
    photo?: ExternalBlob;
    certifications: Array<string>;
    location: string;
}): Promise<{
    bio: string;
    userId: Principal;
    name: string;
    coachingRoles: Array<string>;
    experience: bigint;
    specialty: string;
    positionsCoached: Array<string>;
    photo: [] | [_ExternalBlob];
    certifications: Array<string>;
    location: string;
}> {
    return {
        bio: value.bio,
        userId: value.userId,
        name: value.name,
        coachingRoles: value.coachingRoles,
        experience: value.experience,
        specialty: value.specialty,
        positionsCoached: value.positionsCoached,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        certifications: value.certifications,
        location: value.location
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Attachment>): Promise<Array<_Attachment>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Attachment_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
